### List shopping items
GET http://localhost:8080/shopping-items

### Create new shopping item
POST http://localhost:8080/shopping-items
Content-Type: application/json

{
    "name": "Pie"
}

### Remove shopping item
DELETE http://localhost:8080/shopping-items/39a8a1a2-602e-4ffa-a1ba-6a2cecfe6074
